In [1]:
import numpy as np
import numpy.linalg as LA

a = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [2]:
a**2


matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [3]:
LA.matrix_power(a, 2)


matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [4]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
LA.matrix_power(b, 2)


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [6]:
a = np.array([1, 2, 3, 4, 5, 0])
print("a =", a)


a = [1 2 3 4 5 0]


In [7]:
a1 = np.array([1,2,3,4])
print(
    a1,
    "\n",
    f"size {a1.size}\n shape {a1.shape}\n type {a1.dtype}\n dimension {a1.ndim}",
)

[1 2 3 4] 
 size 4
 shape (4,)
 type int64
 dimension 1


In [8]:
a2 = np.array([[1,2,3,4]])
print(
    a2,
    "\n",
    f"size {a2.size}\n shape {a2.shape}\n type {a2.dtype}\n dimension {a2.ndim}",
)

[[1 2 3 4]] 
 size 4
 shape (1, 4)
 type int64
 dimension 2


In [9]:
a3 = np.array([[1],[2],[3],[4]])
print(
    a3,
    "\n",
    f"size {a3.size}\n shape {a3.shape}\n type {a3.dtype}\n dimension {a3.ndim}",
)


[[1]
 [2]
 [3]
 [4]] 
 size 4
 shape (4, 1)
 type int64
 dimension 2


In [9]:
a4 = np.array(
    [
        [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]],
        [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7]],
        [[2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]],
        [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9]],
    ]
)

print(
    a4,
    "\n",
    f"size {a4.size}\n shape {a4.shape}\n type {a4.dtype}\n dimension {a4.ndim}",
)

[[[0 1 2 3]
  [1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]]

 [[2 3 4 5]
  [3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]]

 [[3 4 5 6]
  [4 5 6 7]
  [5 6 7 8]
  [6 7 8 9]]] 
 size 64
 shape (4, 4, 4)
 type int64
 dimension 3


In [17]:
c = np.array([[1, 2], [3, 4]])
print(c)
c.shape =  (4,)
print(c)


[[1 2]
 [3 4]]
[1 2 3 4]


In [29]:
p = np.pi
d = np.linspace(-p,p, 16)
d2 = np.linspace(1,10, 20)
print(d2)
print(d)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[-3.14159265 -2.72271363 -2.30383461 -1.88495559 -1.46607657 -1.04719755
 -0.62831853 -0.20943951  0.20943951  0.62831853  1.04719755  1.46607657
  1.88495559  2.30383461  2.72271363  3.14159265]
