In [3]:
from sympy import Matrix, symbols, init_printing
init_printing(use_latex="mathjax")
(
    x,
    y,
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
) = symbols("x y a b c d e f g h")
x = Matrix(3, 3, [1, 2, 3, 4, 5, 6, 7, 8, 9])
y = Matrix(2, 3, [1, 2, 3, 4, 5, 6])
print(x)
print(y)

Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Matrix([[1, 2, 3], [4, 5, 6]])


In [4]:
from sympy import expand
m = Matrix([[a, b], [c, d]])
n = Matrix([[e,f],[g,h]])
m + n

⎡a + e  b + f⎤
⎢            ⎥
⎣c + g  d + h⎦

In [5]:
m * n

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

In [5]:
m - n

⎡a - e  b - f⎤
⎢            ⎥
⎣c - g  d - h⎦

In [15]:
x


⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

In [16]:
x.T


⎡1  4  7⎤
⎢       ⎥
⎢2  5  8⎥
⎢       ⎥
⎣3  6  9⎦

In [17]:
y


⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

In [18]:
y.T


⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

In [19]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b = np.diag(np.diag(a))
b


In [8]:
import numpy as np
import numpy.linalg as LA

A = np.arange(1, 10).reshape(3, 3)
A_pow_5 = np.linalg.matrix_power(A, 5)
A_pow_5


array([[121824, 149688, 177552],
       [275886, 338985, 402084],
       [429948, 528282, 626616]])

In [9]:
A**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [10]:
eig = LA.eig(A)
print(eig[0])
print(eig[1])


[ 1.61168440e+01 -1.11684397e+00 -8.58274334e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
def eig_diag(x):
    eig = LA.eig(x)
    e = np.diag(eig[0])
    p = eig[1]
    return e, p


In [ ]:
e = eig_diag(A)
d = e[0]
p = e[1]
ip = LA.inv(p)
A_pow_5 = p @ (d**5) @ ip

print(A_pow_5)
