In [1]:
class Pokemon:
    def __init__(self, name, type1, type2):
        self.name = name
        self.type1 = type1
        self.type2 = type2

    def print_info(self):
        print(
            "名前: "
            + self.name
            + " タイプ1: "
            + self.type1
            + " タイプ2: "
            + self.type2
        )


In [2]:
p1 = Pokemon(name="ピカチュウ", type1="でんき", type2="")
p1.print_info()


名前: ピカチュウ タイプ1: でんき タイプ2: 


In [3]:
p1 = Pokemon(name="ピカチュウ", type1="でんき", type2="")
p2 = Pokemon(name="ピッピ", type1="フェアリー", type2="")
p3 = Pokemon(name="プリン", type1="フェアリー", type2="ノーマル")

print(p1.name)
print(p2.type1)
print(p3.type2)


ピカチュウ
フェアリー
ノーマル


In [4]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
]

for i in p_list:
    i.print_info()


名前: ピカチュウ タイプ1: でんき タイプ2: 
名前: ピッピ タイプ1: フェアリー タイプ2: 
名前: プリン タイプ1: フェアリー タイプ2: ノーマル


In [5]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
]

p_list.append(Pokemon(name="フシギダネ", type1="くさ", type2="どく"))
for i in p_list[2:]:
    i.print_info()


名前: プリン タイプ1: フェアリー タイプ2: ノーマル
名前: フシギダネ タイプ1: くさ タイプ2: どく


## 辞書型


In [6]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}
print(p_dict[25])


ピカチュウ


### 要素の追加と削除


#### 追加


In [7]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}
p_dict[26] = "ライチュウ"
print(p_dict)


{25: 'ピカチュウ', 35: 'ピッピ', 39: 'プリン', 26: 'ライチュウ'}


#### 削除


In [8]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}

print(25 in p_dict)
p_dict.pop(25)
print(25 in p_dict)


True
False


### キーや値の有無を判別する方法


In [9]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}

print(25 in p_dict.keys())
print(26 in p_dict.keys())

print("ピカチュウ" in p_dict.values())
print("ライチュウ" in p_dict.values())


True
False
True
False


### 辞書の要素出力


In [10]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}

for k in p_dict.keys():
    print(k)

for v in p_dict.values():
    print(v)


25
35
39
ピカチュウ
ピッピ
プリン


In [11]:
p_dict = {25: "ピカチュウ", 35: "ピッピ", 39: "プリン"}

p_list = list(map(lambda x: x + "さん", p_dict.values()))

for i in p_list:
    print(i)


ピカチュウさん
ピッピさん
プリンさん


### 辞書型とラムダ式


In [12]:
result = 0
calc_mode = "+"

num1 = 5
num2 = 3

if calc_mode == "+":
    result = num1 + num2
elif calc_mode == "-":
    result = num1 - num2
elif calc_mode == "*":
    result = num1 * num2
elif calc_mode == "/":
    result = num1 / num2
elif calc_mode == "%":
    result = num1 % num2

print(result)


8


In [13]:
calc_dic = {
    "+": lambda x, y: x + y,
    "-": lambda x, y: x - y,
    "*": lambda x, y: x * y,
    "/": lambda x, y: x / y,
    "%": lambda x, y: x % y,
}
num1 = 5
num2 = 3
print(calc_dic["+"](num1, num2))
print(calc_dic["*"](num1, num2))
print(calc_dic["%"](num1, num2))
print(calc_dic["-"](num1, num2))
print(calc_dic["/"](num1, num2))


8
15
2
2
1.6666666666666667


### 練習


In [14]:
p_dict = {
    25: "ピカチュウ",
    26: "ライチュウ",
    35: "ピッピ",
    36: "ピクシー",
    39: "プリン",
    40: "プクリン",
}
p = p_dict[36]
print(p)


ピクシー


In [15]:
p_dict = {
    25: "ピカチュウ",
    26: "ライチュウ",
    35: "ピッピ",
    36: "ピクシー",
    39: "プリン",
    40: "プクリン",
}

p_l = filter(lambda x: "チュウ" in x, p_dict.values())
for i in p_l:
    print(i)


ピカチュウ
ライチュウ


## タプル


### タプル型の書き方と参照方法


In [16]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")
print(p_tuple[0])
print(p_tuple[1])


ピカチュウ
ピッピ


### メソッド

イミュータブルなので、参照系のメソッドしか無い。


In [17]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン", "プリン")

print(p_tuple.count("プリン"))
print(p_tuple.index("ピッピ"))


2
1


### 要素の出力


In [18]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")

for i in p_tuple:
    print(i)


ピカチュウ
ピッピ
プリン


In [19]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")

for i in range(len(p_tuple)):
    print(p_tuple[i])


ピカチュウ
ピッピ
プリン


### タプル型を引数として受け取れる関数

|        |
| :----: |
|  all   |
|  any   |
|  len   |
|  max   |
|  min   |
| sorted |
|  sum   |

map と filter は使えない


In [20]:
n_tuple = (5, 2, 3, 1, 4)
print(max(n_tuple))
print(any(x > 3 for x in n_tuple))
print(all(x > 3 for x in n_tuple))
print(sorted(n_tuple))


5
True
False
[1, 2, 3, 4, 5]


### 練習


In [21]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")

for i in p_tuple:
    print(len(i))


5
3
3


In [22]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")
count = ""
for i in p_tuple:
    if len(count) < len(i):
        count = i

print(count)


ピカチュウ


In [23]:
p_tuple = ("ピカチュウ", "ピッピ", "プリン")

print(max(p_tuple, key=len))


ピカチュウ


## zip 関数と型変換関数


### zip 関数

2 つの関数を一つの要素にまとめる


In [24]:
# 　zipを使わずに2つのリストを連結

p_list = ["ピカチュウ", "ピッピ", "ゼニガメ", "ヒトカゲ"]
type_list = ["でんき", "フェアリー", "みず", "ほのお"]
p_type_list = []
for i in range(len(p_list)):
    p_type_list.append(p_list[i] + ":" + type_list[i])

for i in p_type_list:
    print(i)


ピカチュウ:でんき
ピッピ:フェアリー
ゼニガメ:みず
ヒトカゲ:ほのお


In [25]:
p_list = ["ピカチュウ", "ピッピ", "ゼニガメ", "ヒトカゲ"]
type_list = ["でんき", "フェアリー", "みず", "ほのお"]
p_type_list = list(zip(p_list, type_list))
p_type_list2 = zip(p_list, type_list)

for i in p_type_list:
    print(i[0] + ":" + i[1])


ピカチュウ:でんき
ピッピ:フェアリー
ゼニガメ:みず
ヒトカゲ:ほのお


In [26]:
# zipの戻り値の型を確認
for i in p_type_list:
    print(i)


('ピカチュウ', 'でんき')
('ピッピ', 'フェアリー')
('ゼニガメ', 'みず')
('ヒトカゲ', 'ほのお')


- zip は遅延評価
  - for ループに渡されたり list にラップされるなどの反復処理が実行されるまで受け取った要素を処理しない。


In [27]:
for i in p_type_list2:
    print(i)


('ピカチュウ', 'でんき')
('ピッピ', 'フェアリー')
('ゼニガメ', 'みず')
('ヒトカゲ', 'ほのお')


In [28]:
print(p_type_list)
print(p_type_list2)


[('ピカチュウ', 'でんき'), ('ピッピ', 'フェアリー'), ('ゼニガメ', 'みず'), ('ヒトカゲ', 'ほのお')]


### list 関数


In [29]:
p_t = ("ピカチュウ", "ピッピ", "プリン")
p_l = list(p_t)

print(p_t)

print(p_l)


('ピカチュウ', 'ピッピ', 'プリン')
['ピカチュウ', 'ピッピ', 'プリン']


In [30]:
p_d = {"ピカチュウ": "でんき", "ピッピ": "フェアリー", "ゼニガメ": "みず"}

p_l = list(p_d)
print(p_l)
p_l2 = list(p_d.values())
print(p_l2)
p_l3 = list(p_d.keys())
print(p_l3)


['ピカチュウ', 'ピッピ', 'ゼニガメ']
['でんき', 'フェアリー', 'みず']
['ピカチュウ', 'ピッピ', 'ゼニガメ']


デフォルトでキーを抽出してリスト化する。  
略さずに宣言したほうがよさげ？


### tuple 関数


In [31]:
p_l = ["ピカチュウ", "ピッピ", "プリン"]

p_t = tuple(p_l)
print(p_t)


('ピカチュウ', 'ピッピ', 'プリン')


In [32]:
p_d = {"ピカチュウ": "でんき", "ピッピ": "フェアリー", "ゼニガメ": "みず"}

p_t = tuple(p_d)
print(p_t)
p_t2 = tuple(p_d.keys())
print(p_t2)
p_t3 = tuple(p_d.values())
print(p_t3)


('ピカチュウ', 'ピッピ', 'ゼニガメ')
('ピカチュウ', 'ピッピ', 'ゼニガメ')
('でんき', 'フェアリー', 'みず')


### dict 関数


In [33]:
p_l = [["ピカチュウ", "でんき"], ["ピッピ", "フェアリー"], ["ゼニガメ", "みず"]]
p_d = dict(p_l)
print(p_d)


{'ピカチュウ': 'でんき', 'ピッピ': 'フェアリー', 'ゼニガメ': 'みず'}


In [34]:
p_t = (("ピカチュウ", "でんき"), ("ピッピ", "フェアリー"), ("ゼニガメ", "みず"))
p_d = dict(p_t)
print(p_t)


(('ピカチュウ', 'でんき'), ('ピッピ', 'フェアリー'), ('ゼニガメ', 'みず'))


In [35]:
p_list = ["ピカチュウ", "ピッピ", "ゼニガメ", "ヒトカゲ"]
type_list = ["でんき", "フェアリー", "みず", "ほのお"]

p_d = dict(zip(p_list, type_list))

print(p_d)


{'ピカチュウ': 'でんき', 'ピッピ': 'フェアリー', 'ゼニガメ': 'みず', 'ヒトカゲ': 'ほのお'}


上記リストの組み合わせ以外にタプル同士、タプルとリストの組み合わせも処理できる。


### 練習


In [36]:
n1 = [1, 2, 3, 4, 5]
n2 = [5, 6, 7, 8, 9]

for i in zip(n1, n2):
    print(i[0] + i[1])


6
8
10
12
14


In [37]:
no_list = [1, 2, 3]
p_list = ["ピチュー", "ピカチュウ", "ライチュウ"]

n_d = dict(zip(no_list, p_list))

for i in n_d.values():
    print(i)


ピチュー
ピカチュウ
ライチュウ


## クラスを用いた関数の使用


In [38]:
class Pokemon:
    def __init__(self, name, type1, type2):
        self.name = name
        self.type1 = type1
        self.type2 = type2

    def print_info(self):
        print(
            "名前: "
            + self.name
            + " タイプ1: "
            + self.type1
            + " タイプ2: "
            + self.type2
        )


In [39]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]

for i in p_list:
    i.print_info()


名前: ピカチュウ タイプ1: でんき タイプ2: 
名前: ピッピ タイプ1: フェアリー タイプ2: 
名前: プリン タイプ1: フェアリー タイプ2: ノーマル
名前: ゼニガメ タイプ1: みず タイプ2: 
名前: ヒトカゲ タイプ1: ほのお タイプ2: 


In [40]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]

info_list = list(map(lambda x: x.print_info(), p_list))

for i in info_list:
    i


名前: ピカチュウ タイプ1: でんき タイプ2: 
名前: ピッピ タイプ1: フェアリー タイプ2: 
名前: プリン タイプ1: フェアリー タイプ2: ノーマル
名前: ゼニガメ タイプ1: みず タイプ2: 
名前: ヒトカゲ タイプ1: ほのお タイプ2: 


In [41]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]

info_list = list(
    map(
        lambda x: "名前: " + x.name + " タイプ1: " + x.type1 + " タイプ2: " + x.type2,
        p_list,
    )
)

for i in info_list:
    print(i)


名前: ピカチュウ タイプ1: でんき タイプ2: 
名前: ピッピ タイプ1: フェアリー タイプ2: 
名前: プリン タイプ1: フェアリー タイプ2: ノーマル
名前: ゼニガメ タイプ1: みず タイプ2: 
名前: ヒトカゲ タイプ1: ほのお タイプ2: 


In [42]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]

info_list = list(filter(lambda x: x.type2 != "", p_list))

for i in info_list:
    i.print_info()


名前: プリン タイプ1: フェアリー タイプ2: ノーマル


In [43]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]


info_list = sorted(p_list, key=lambda x: x.name)

for i in info_list:
    print(i.name)


ゼニガメ
ヒトカゲ
ピカチュウ
ピッピ
プリン


In [44]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]


info_list = sorted(p_list, key=lambda x: len(x.name))

for i in info_list:
    print(i.name)


ピッピ
プリン
ゼニガメ
ヒトカゲ
ピカチュウ


### 練習


In [45]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]


info_list = list(filter(lambda x: "ピ" in x.name, p_list))

for i in info_list:
    i.print_info()


名前: ピカチュウ タイプ1: でんき タイプ2: 
名前: ピッピ タイプ1: フェアリー タイプ2: 


In [46]:
p_list = [
    Pokemon(name="ピカチュウ", type1="でんき", type2=""),
    Pokemon(name="ピッピ", type1="フェアリー", type2=""),
    Pokemon(name="プリン", type1="フェアリー", type2="ノーマル"),
    Pokemon(name="ゼニガメ", type1="みず", type2=""),
    Pokemon(name="ヒトカゲ", type1="ほのお", type2=""),
]


info_list = list(sorted(map(lambda x: x.name + "さん", p_list), key=len))

for i in info_list:
    print(i)


ピッピさん
プリンさん
ゼニガメさん
ヒトカゲさん
ピカチュウさん


## pandas の DataFrame の使い方

- 1 次元データ
  - Series
- 2 次元データ
  - DataFrame


In [47]:
import pandas as pd

p_name_list = ["ピカチュウ", "ピッピ", "プリン"]
df = pd.DataFrame(data=p_name_list)
print(df)


       0
0  ピカチュウ
1    ピッピ
2    プリン


In [48]:
p_name_list = ["ピカチュウ", "ピッピ", "プリン"]
col = ["ポケモン名"]
no_list = ["25", "35", "39"]
df = pd.DataFrame(data=p_name_list, index=no_list, columns=col)
print(df)


    ポケモン名
25  ピカチュウ
35    ピッピ
39    プリン


In [49]:
p_name_list = [
    [" ピカチュウ", "ピッピ", "プリン"],
    ["でんき", "フェアリー", "フェアリー"],
    ["", "", "ノーマル"],
]
col = ["ポケモン名", "タイプ1", "タイプ2"]
no_list = ["25", "35", "39"]
df = pd.DataFrame(data=p_name_list, index=no_list, columns=col)
print(df)


     ポケモン名   タイプ1   タイプ2
25   ピカチュウ    ピッピ    プリン
35     でんき  フェアリー  フェアリー
39                  ノーマル


### 辞書型から DataFrame に変換する


キーを列名にする。DataFrame コンストラクタを使用


In [50]:
import pandas as pd

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame(p_dict)
print(df)


   ポケモン名   タイプ1  タイプ2
0  ピカチュウ    でんき      
1    ピッピ  フェアリー      
2    プリン  フェアリー  ノーマル


In [51]:
import pandas as pd

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame(p_dict)
print(df)


   ポケモン名   タイプ1  タイプ2
0  ピカチュウ    でんき      
1    ピッピ  フェアリー      
2    プリン  フェアリー  ノーマル


In [52]:
import pandas as pd

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame(p_dict, index=[25, 35, 38])
print(df)


    ポケモン名   タイプ1  タイプ2
25  ピカチュウ    でんき      
35    ピッピ  フェアリー      
38    プリン  フェアリー  ノーマル


キーを行名にする


In [53]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame.from_dict(p_dict, orient="index")
print(df)


                     0           1           2
ポケモン名  ピカチュウ      ピッピ      プリン
タイプ1         でんき  フェアリー  フェアリー
タイプ2                               ノーマル


### DataFrame から辞書型に変換する


In [54]:
import pandas as pd

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame(p_dict)
print(df)

# 引数を指定しない場合は辞書の各要素が辞書型になる
df_dict = df.to_dict()

print(df_dict)


   ポケモン名     タイプ1   タイプ2
0  ピカチュウ      でんき          
1      ピッピ  フェアリー          
2      プリン  フェアリー  ノーマル
{'ポケモン名': {0: 'ピカチュウ', 1: 'ピッピ', 2: 'プリン'}, 'タイプ1': {0: 'でんき', 1: 'フェアリー', 2: 'フェアリー'}, 'タイプ2': {0: '', 1: '', 2: 'ノーマル'}}


In [55]:
import pandas as pd

p_dict = {
    "ポケモン名": ["ピカチュウ", "ピッピ", "プリン"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー"],
    "タイプ2": ["", "", "ノーマル"],
}


df = pd.DataFrame(p_dict)
print(df.to_dict(orient="list"))


{'ポケモン名': ['ピカチュウ', 'ピッピ', 'プリン'], 'タイプ1': ['でんき', 'フェアリー', 'フェアリー'], 'タイプ2': ['', '', 'ノーマル']}


要素をリスト型にして変換することも可能だが、インデックスの値が自動的に削除されるコトに注意。


### DataFrame の単独の値を取得


In [56]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": ["25", "35", "38", "1", "4", "7"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

print(df)


            No     タイプ1   タイプ2
ピカチュウ  25      でんき          
ピッピ      35  フェアリー          
プリン      38  フェアリー  ノーマル
フシギダネ   1        くさ      どく
ヒトカゲ     4      ほのお          
ゼニガメ     7        みず          


In [57]:
print(df.at["ピカチュウ", "タイプ1"])


でんき


In [58]:
print(df.iat[0, 1])


でんき


### DataFrame の値を範囲で取得


In [59]:
print(df.loc["ピカチュウ", :])


No             25
タイプ1    でんき
タイプ2          
Name: ピカチュウ, dtype: object


In [60]:
print(df.loc["ピカチュウ":"プリン", :])


            No     タイプ1   タイプ2
ピカチュウ  25      でんき          
ピッピ      35  フェアリー          
プリン      38  フェアリー  ノーマル


In [61]:
print(df.loc[["ピカチュウ", "プリン"], :])


            No     タイプ1   タイプ2
ピカチュウ  25      でんき          
プリン      38  フェアリー  ノーマル


In [62]:
print(df.loc[:, :"タイプ1"])


            No     タイプ1
ピカチュウ  25      でんき
ピッピ      35  フェアリー
プリン      38  フェアリー
フシギダネ   1        くさ
ヒトカゲ     4      ほのお
ゼニガメ     7        みず


In [63]:
print(df.iloc[0:3, 1:])


               タイプ1   タイプ2
ピカチュウ      でんき          
ピッピ      フェアリー          
プリン      フェアリー  ノーマル


### head メソッドと tail メソッド


In [64]:
print(df.head(3))


            No     タイプ1   タイプ2
ピカチュウ  25      でんき          
ピッピ      35  フェアリー          
プリン      38  フェアリー  ノーマル


In [65]:
print(df.tail(3))


           No タイプ1 タイプ2
フシギダネ  1    くさ    どく
ヒトカゲ    4  ほのお        
ゼニガメ    7    みず        


### 条件を指定しデータを取得する


In [66]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": [25, 35, 38, 1, 4, 7],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

print(df.query('タイプ1 == "フェアリー"'))


        No     タイプ1   タイプ2
ピッピ  35  フェアリー          
プリン  38  フェアリー  ノーマル


In [67]:
print(df.query('タイプ1 == ["フェアリー", "みず"]'))


          No     タイプ1   タイプ2
ピッピ    35  フェアリー          
プリン    38  フェアリー  ノーマル
ゼニガメ   7        みず          


In [68]:
print(df.query("No > 8"))


            No     タイプ1   タイプ2
ピカチュウ  25      でんき          
ピッピ      35  フェアリー          
プリン      38  フェアリー  ノーマル


### ラベル名の取得と抽出方法


In [69]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": ["25", "35", "38", "1", "4", "7"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

for i in df.index:
    print(i)


ピカチュウ
ピッピ
プリン
フシギダネ
ヒトカゲ
ゼニガメ


In [70]:
for i in df.columns:
    print(i)


No
タイプ1
タイプ2


In [71]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": ["25", "35", "38", "1", "4", "7"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])


df_like = df.filter(like="プ", axis=0)
print(df_like)


        No     タイプ1   タイプ2
プリン  38  フェアリー  ノーマル


In [72]:
df_like = df.filter(like="プ", axis=1)
print(df_like)


               タイプ1   タイプ2
ピカチュウ      でんき          
ピッピ      フェアリー          
プリン      フェアリー  ノーマル
フシギダネ        くさ      どく
ヒトカゲ        ほのお          
ゼニガメ          みず          


### 練習


In [73]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": ["25", "35", "38", "1", "4", "7"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

p_info = df.query('タイプ2 == ""')
print(p_info)


            No     タイプ1 タイプ2
ピカチュウ  25      でんき        
ピッピ      35  フェアリー        
ヒトカゲ     4      ほのお        
ゼニガメ     7        みず        


In [74]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": ["25", "35", "38", "1", "4", "7"],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

print(df.tail(3))


           No タイプ1 タイプ2
フシギダネ  1    くさ    どく
ヒトカゲ    4  ほのお        
ゼニガメ    7    みず        


In [75]:
df.iloc[3:6]


No タイプ1 タイプ2
フシギダネ  1    くさ    どく
ヒトカゲ    4  ほのお        
ゼニガメ    7    みず

## Pandas の Series の使い方


In [76]:
import pandas as pd

p_name_list = ["ピカチュウ", "ピッピ", "プリン"]
s = pd.Series(data=p_name_list)

print(s)


0    ピカチュウ
1        ピッピ
2        プリン
dtype: object


In [77]:
# インデックスも指定してみる

s = pd.Series(data=p_name_list, index=[25, 35, 38])
print(s)


25    ピカチュウ
35        ピッピ
38        プリン
dtype: object


二次元リストを渡すと要素がリストになる


In [78]:
p_name_list = [["ピカチュウ", "ライチュウ"], ["ピッピ", "ピクシー"], ["プリン", "プクリン"]]
s = pd.Series(data=p_name_list)
print(s)


0    [ピカチュウ, ライチュウ]
1          [ピッピ, ピクシー]
2          [プリン, プクリン]
dtype: object


list 関数で復元できる


In [79]:
print(list(s))


[['ピカチュウ', 'ライチュウ'], ['ピッピ', 'ピクシー'], ['プリン', 'プクリン']]


### 辞書型を Series に変換する


In [80]:
p_d = {"ピカチュウ": "でんき", "ピッピ": "フェアリー", "ゼニガメ": "みず"}

s = pd.Series(p_d)

print(s)


ピカチュウ        でんき
ピッピ        フェアリー
ゼニガメ            みず
dtype: object


In [81]:
# to_dictメソッドでもとに戻せる

rest = s.to_dict()
print(rest)


{'ピカチュウ': 'でんき', 'ピッピ': 'フェアリー', 'ゼニガメ': 'みず'}


### Series から DataFrame に変換する


In [82]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {"ピカチュウ": "でんき", "ピッピ": "フェアリー", "ゼニガメ": "みず"}

s = pd.Series(p_dict)
df = pd.DataFrame(s, columns=["タイプ1"])
print(s)
print(df)


ピカチュウ        でんき
ピッピ        フェアリー
ゼニガメ            みず
dtype: object
               タイプ1
ピカチュウ      でんき
ピッピ      フェアリー
ゼニガメ          みず


### DataFrame から Series に変換する


In [83]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": [25, 35, 38, 1, 4, 7],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

s = df.loc[:, "タイプ1"]
print(s)
print(type(s))


ピカチュウ        でんき
ピッピ        フェアリー
プリン        フェアリー
フシギダネ          くさ
ヒトカゲ          ほのお
ゼニガメ            みず
Name: タイプ1, dtype: object
<class 'pandas.core.series.Series'>


スライスを選ぶと Series のようにデータ抽出しても DataFrame になる


In [84]:
s = df.loc[:, "タイプ2":]
print(s)
print(type(s))


             タイプ2
ピカチュウ          
ピッピ              
プリン      ノーマル
フシギダネ      どく
ヒトカゲ            
ゼニガメ            
<class 'pandas.core.frame.DataFrame'>


In [85]:
import pandas as pd

pd.set_option("display.unicode.east_asian_width", True)

p_dict = {
    "No": [25, 35, 38, 1, 4, 7],
    "タイプ1": ["でんき", "フェアリー", "フェアリー", "くさ", "ほのお", "みず"],
    "タイプ2": ["", "", "ノーマル", "どく", "", ""],
}


df = pd.DataFrame(p_dict, ["ピカチュウ", "ピッピ", "プリン", "フシギダネ", "ヒトカゲ", "ゼニガメ"])

s = df.loc[:, ["タイプ1"]]
print(s)
print(type(s))


               タイプ1
ピカチュウ      でんき
ピッピ      フェアリー
プリン      フェアリー
フシギダネ        くさ
ヒトカゲ        ほのお
ゼニガメ          みず
<class 'pandas.core.frame.DataFrame'>


### Series から単独の値を取得


In [86]:
import pandas as pd


p_dict = {"ピカチュウ": "でんき", "ピッピ": "フェアリー", "ゼニガメ": "みず"}
s = pd.Series(p_dict)

print(s.at["ピッピ"])
print(s.iat[0])


フェアリー
でんき


### Series から値のすべてを取得


In [87]:
import pandas as pd


p_dict = {
    "ピカチュウ": "でんき",
    "ピッピ": "フェアリー",
    "ゼニガメ": "みず",
    "ヒトカゲ": "ほのお",
    "ライチュウ": "でんき",
}
s = pd.Series(p_dict)

for i in s:
    print(i)

でんき
フェアリー
みず
ほのお
でんき


In [88]:
# インデックスはキーを指定して取得する

for i in s.keys():
    print(i)

ピカチュウ
ピッピ
ゼニガメ
ヒトカゲ
ライチュウ


### 条件を指定してデータを取得する

In [89]:
p_dict = {
    "ピカチュウ": "でんき",
    "ピッピ": "フェアリー",
    "ゼニガメ": "みず",
    "ヒトカゲ": "ほのお",
    "ライチュウ": "でんき",
}
s = pd.Series(p_dict)

print(s[s == "でんき"])

ピカチュウ    でんき
ライチュウ    でんき
dtype: object


In [90]:
print(s == "でんき")

ピカチュウ     True
ピッピ        False
ゼニガメ      False
ヒトカゲ      False
ライチュウ     True
dtype: bool


In [91]:
s_like = s.filter(like="ピ")
print(s_like)

ピカチュウ        でんき
ピッピ        フェアリー
dtype: object


### 練習


In [92]:
import pandas as pd

p_dict = {"ピカチュウ": 25, "ピッピ": 35, "ゼニガメ": 7, "ヒトカゲ": 4, "ライチュウ": 26}

s = pd.Series(p_dict)

print(s[s >= 25])


ピカチュウ    25
ピッピ        35
ライチュウ    26
dtype: int64


In [93]:
p_dict = {
    "ピカチュウ": "でんき",
    "ピッピ": "フェアリー",
    "ゼニガメ": "みず",
    "ヒトカゲ": "ほのお",
    "ライチュウ": "でんき",
}
s = pd.Series(p_dict)

s = s.at["ゼニガメ"]

print(s)

みず


## NumPyについて

### 同じ要素で初期化

In [94]:
import numpy as np

num_np = np.zeros(3)

print(num_np)

[0. 0. 0.]


In [95]:
num_np = np.zeros(3, dtype=np.int_)

print(num_np)
print(num_np.dtype)

[0 0 0]
int64


In [96]:
num_np = np.zeros((3,2), dtype=np.int_)
print(num_np)

[[0 0]
 [0 0]
 [0 0]]


In [97]:
# 1で埋める。これもデフォルトはfloat

num_np = np.ones((3,2))
print(num_np)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [98]:
# 任意の値で埋める

num_np = np.full(shape=(3,2), fill_value=10)
print(num_np)

[[10 10]
 [10 10]
 [10 10]]


In [99]:
num_np = np.full((3,2), 10.0)
print(num_np)

[[10. 10.]
 [10. 10.]
 [10. 10.]]


### arangeとreshape

In [100]:
#　rangeと同じく開始と終了とステップを指定できる
num_np = np.arange(1,10,2)
print(num_np)

[1 3 5 7 9]


In [101]:

num_np = np.arange(1.,10,2)
print(num_np)

[1. 3. 5. 7. 9.]


In [102]:
num_np = np.arange(10).reshape(2,5)
print(num_np)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [103]:
num_np = np.arange(10).reshape(5,2)

print(num_np)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [104]:
num_np = np.arange(1,28).reshape(3,3,3)
print(num_np)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [105]:
num_np = np.arange(64).reshape(4,4,4)
print(num_np)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [106]:
num_np = np.arange(125).reshape(5,5,5)
print(num_np)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]


In [107]:
print(np.zeros_like(num_np))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [108]:
print(np.ones_like(num_np))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [109]:
print(np.full_like(num_np, 10))

[[[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]

 [[10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]
  [10 10 10 10 10]]]


### 要素の取得方法

In [110]:
num_np = np.arange(6)
print(num_np)
print(num_np[4])

for i in range(len(num_np)):
    print(num_np[i])

[0 1 2 3 4 5]
4
0
1
2
3
4
5


In [111]:
print(num_np[3:6])

[3 4 5]


基本的にリストと変わらない。  
二次元配列は行と列を指定する。

In [112]:
num_np = np.arange(6).reshape(3,2)

print(num_np)
print(num_np[2][1])

[[0 1]
 [2 3]
 [4 5]]
5


In [113]:
len(num_np[1])

2

In [114]:
for i in num_np:
    print(i)

[0 1]
[2 3]
[4 5]


In [115]:
for i in range(len(num_np)):
    for j in range(len(num_np[i])):
        print(num_np[i][j])

0
1
2
3
4
5


### 要素の設定方法

In [1]:
import numpy as np

num_np = np.arange(6)
num_np[3] = 10
print(num_np)

[ 0  1  2 10  4  5]


In [2]:
num_np = np.arange(6).reshape(3,2)

num_np[1,1] = 10
print(num_np)

[[ 0  1]
 [ 2 10]
 [ 4  5]]
